name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Go Test
      run: go test -v ./internal/...

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Web
      run: |
        cd web
        npm ci
        npm run build
